/* eslint-disable */
/* prettier-ignore */
// biome-ignore format: off
// biome-ignore lint: off
// @ts-nocheck
// Generated by unplugin-svg-component
declare module '~virtual/svg-component' {
  const SvgIcon: import("vue").DefineComponent<{
      name: {
          type: import("vue").PropType<"dashboard" | "end" | "fullscreen-exit" | "fullscreen" | "keyboard-down" | "keyboard-enter" | "keyboard-esc" | "keyboard-up" | "run" | "search" | "start" | "data-statis/github" | "data-statis/github_2020" | "data-statis/github_2021" | "data-statis/github_2022" | "data-statis/github_2023" | "data-statis/github_2024" | "data-statis/grid" | "data-statis/year_2020" | "data-statis/year_2021" | "data-statis/year_2022" | "data-statis/year_2023" | "data-statis/year_2024">;
          default: string;
          required: true;
      };
  }, {}, unknown, {}, {}, import("vue").ComponentOptionsMixin, import("vue").ComponentOptionsMixin, {}, string, import("vue").VNodeProps & import("vue").AllowedComponentProps & import("vue").ComponentCustomProps, Readonly<import("vue").ExtractPropTypes<{
      name: {
          type: import("vue").PropType<"dashboard" | "end" | "fullscreen-exit" | "fullscreen" | "keyboard-down" | "keyboard-enter" | "keyboard-esc" | "keyboard-up" | "run" | "search" | "start" | "data-statis/github" | "data-statis/github_2020" | "data-statis/github_2021" | "data-statis/github_2022" | "data-statis/github_2023" | "data-statis/github_2024" | "data-statis/grid" | "data-statis/year_2020" | "data-statis/year_2021" | "data-statis/year_2022" | "data-statis/year_2023" | "data-statis/year_2024">;
          default: string;
          required: true;
      };
  }>>, {
      name: "dashboard" | "end" | "fullscreen-exit" | "fullscreen" | "keyboard-down" | "keyboard-enter" | "keyboard-esc" | "keyboard-up" | "run" | "search" | "start" | "data-statis/github" | "data-statis/github_2020" | "data-statis/github_2021" | "data-statis/github_2022" | "data-statis/github_2023" | "data-statis/github_2024" | "data-statis/grid" | "data-statis/year_2020" | "data-statis/year_2021" | "data-statis/year_2022" | "data-statis/year_2023" | "data-statis/year_2024";
  }>;
  export const svgNames: ["dashboard", "end", "fullscreen-exit", "fullscreen", "keyboard-down", "keyboard-enter", "keyboard-esc", "keyboard-up", "run", "search", "start", "data-statis/github", "data-statis/github_2020", "data-statis/github_2021", "data-statis/github_2022", "data-statis/github_2023", "data-statis/github_2024", "data-statis/grid", "data-statis/year_2020", "data-statis/year_2021", "data-statis/year_2022", "data-statis/year_2023", "data-statis/year_2024"];
  export type SvgName = "dashboard" | "end" | "fullscreen-exit" | "fullscreen" | "keyboard-down" | "keyboard-enter" | "keyboard-esc" | "keyboard-up" | "run" | "search" | "start" | "data-statis/github" | "data-statis/github_2020" | "data-statis/github_2021" | "data-statis/github_2022" | "data-statis/github_2023" | "data-statis/github_2024" | "data-statis/grid" | "data-statis/year_2020" | "data-statis/year_2021" | "data-statis/year_2022" | "data-statis/year_2023" | "data-statis/year_2024";
  export default SvgIcon;
}
